"""empty message

Revision ID: 0772e371e293
Revises: c99d0dc9c875
Create Date: 2019-07-03 10:21:08.218992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0772e371e293'
down_revision = 'c99d0dc9c875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'newcolumn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('newcolumn', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
