"""empty message

Revision ID: 22dbbad1373d
Revises: 60751cde36c9
Create Date: 2019-07-10 17:40:48.264504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dbbad1373d'
down_revision = '60751cde36c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user1_Id_user2_Id', 'relationships', ['user1_Id', 'user2_Id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user1_Id_user2_Id', 'relationships', type_='unique')
    # ### end Alembic commands ###
