"""empty message

Revision ID: 4a8001c775b9
Revises: 90c679497f21
Create Date: 2019-07-25 20:44:02.310019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a8001c775b9'
down_revision = '90c679497f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_path', sa.String(length=200), nullable=True))
    op.alter_column('posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('posts', 'image_id')
    op.add_column('users', sa.Column('image_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_path')
    op.add_column('posts', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('posts', 'image_path')
    # ### end Alembic commands ###
