"""relastionship table-add two more columns

Revision ID: 60751cde36c9
Revises: 2c0176db11a7
Create Date: 2019-07-09 22:37:10.571921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60751cde36c9'
down_revision = '2c0176db11a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('action_by', sa.Integer(), nullable=True))
    op.add_column('relationships', sa.Column('status', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'relationships', 'users', ['action_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_column('relationships', 'status')
    op.drop_column('relationships', 'action_by')
    # ### end Alembic commands ###
