"""empty message

Revision ID: 670ea5c6d6b0
Revises: 22dbbad1373d
Create Date: 2019-07-19 21:34:41.468228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670ea5c6d6b0'
down_revision = '22dbbad1373d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###
