"""empty message

Revision ID: c64e2c7405ae
Revises: 670ea5c6d6b0
Create Date: 2019-07-19 21:37:13.443825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64e2c7405ae'
down_revision = '670ea5c6d6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
