"""empty message

Revision ID: c99d0dc9c875
Revises: b4bb2dc5dacf
Create Date: 2019-07-03 10:03:22.066469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99d0dc9c875'
down_revision = 'b4bb2dc5dacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('newcolumn', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'newcolumn')
    # ### end Alembic commands ###
